#!/usr/bin/env python3
"""
Print all registered task with one Format example each, saved as tasks_overview.md.

Usage: 
    python scripts/print_tasks_overview.py [--output tasks_overview.md]
"""
import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from tasks.registry import discover_tasks, get_task, list_tasks

# All task identifiers mirroring non_comp_names + new task in analyze_real_tasks.py
ALL_TASKS = [
    # Base task
    "basic_arithmetic",
    "copying",
    "math",
    "token_reversal",
    "string_analogy",
    # simple ICL subtasks
    "simple_icl:uppercase",
    "simple_icl:lowercase",
    "simple_icl:first_letter",
    "simple_icl:translate_eng_fr",
    "simple_icl:translate_fr_eng",
    "simple_icl:translate_sp_eng",
    "simple_icl:singular_to_plural",
    "simple_icl:country_to_capital",
    "simple_icl:country_to_currency",
    # TextFRCT subtasks
    "textfrct:CV1",
    "textfrct:CV2",
    "textfrct:CV3",
    "textfrct:I1",
    "textfrct:I2",
    "textfrct:MA2",
    "textfrct:MA3",
    "textfrct:RG1",
    "textfrct:RG2",
    "textfrct:RG3",
    "textfrct:RL1",
    "textfrct:RL3",
    "textfrct:RL4",
    "textfrct:V1",
    "textfrct:V2",
    "textfrct:V3",
    "textfrct:V4",
    "textfrct:V5",
    # new elemental task
    "multistep_arithmetic:two_step",
    "multistep_arithmetic:three_step",
    "logical_ops:negation",
    "logical_ops:conjunction",
    "logical_ops:conditional",
    "fact_extraction:extract_entity",
    "fact_extraction:extract_number",
    "fact_extraction:extract_location",
    "coreference:pronoun_simple",
    "coreference:pronoun_hard",
    # compositional task (training pair)
    "compositional:lower_reverse_first",
    "compositional:upper_reverse_last",
]

# human-readable class labels
CATEGORY_MAP = {
    "basic_arithmetic": "Arithmetic",
    "math": "Arithmetic",
    "multistep_arithmetic:two_step": "Arithmetic",
    "multistep_arithmetic:three_step": "Arithmetic",
    "copying": "String Manipulation",
    "token_reversal": "String Manipulation",
    "string_analogy": "String Manipulation",
    "simple_icl:uppercase": "String Manipulation",
    "simple_icl:lowercase": "String Manipulation",
    "simple_icl:first_letter": "String Manipulation",
    "textfrct:CV1": "String Manipulation",
    "textfrct:CV2": "String Manipulation",
    "textfrct:CV3": "String Manipulation",
    "textfrct:RL4": "String Manipulation",
    "simple_icl:translate_eng_fr": "Translation",
    "simple_icl:translate_fr_eng": "Translation",
    "simple_icl:translate_sp_eng": "Translation",
    "simple_icl:singular_to_plural": "Grammatical",
    "simple_icl:country_to_capital": "Factual Lookup",
    "simple_icl:country_to_currency": "Factual Lookup",
    "textfrct:I1": "Pattern Recognition",
    "textfrct:I2": "Pattern Recognition",
    "textfrct:MA2": "Associative Memory",
    "textfrct:MA3": "Associative Memory",
    "textfrct:RG1": "Arithmetic",
    "textfrct:RG2": "Arithmetic",
    "textfrct:RG3": "Arithmetic",
    "textfrct:RL1": "Logic",
    "textfrct:RL3": "Logic",
    "textfrct:V1": "Vocabulary",
    "textfrct:V2": "Vocabulary",
    "textfrct:V3": "Vocabulary",
    "textfrct:V4": "Vocabulary",
    "textfrct:V5": "Vocabulary",
    "logical_ops:negation": "Logic",
    "logical_ops:conjunction": "Logic",
    "logical_ops:conditional": "Logic",
    "fact_extraction:extract_entity": "Reading Comprehension",
    "fact_extraction:extract_number": "Reading Comprehension",
    "fact_extraction:extract_location": "Reading Comprehension",
    "coreference:pronoun_simple": "Reading Comprehension",
    "coreference:pronoun_hard": "Reading Comprehension",
    "compositional:lower_reverse_first": "Compositional",
    "compositional:upper_reverse_last": "Compositional",
}

NUM_SHOTS = 3


def _slug(name: str) -> str:
    return name.replace(":", "_").replace(" ", "_")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default="tasks_overview.md",
                        help="Output markdown file (default: tasks_overview.md)")
    args = parser.parse_args()

    discover_tasks()

    lines = []
    lines.append("# ElementalTask — Task Overview\n")
    lines.append(
        "Each task is shown with a few-shot prompt (demonstrations) "
        f"followed by one query and its expected answer.\n"
    )
    lines.append(f"> Generated by `scripts/print_tasks_overview.py`\n")
    lines.append("---\n")

    # group by category for clean presentation
    by_category: dict[str, list[str]] = {}
    for task_name in ALL_TASKS:
        cat = CATEGORY_MAP.get(task_name, "Other")
        by_category.setdefault(cat, []).append(task_name)

    category_order = [
        "Arithmetic", "String Manipulation", "Translation", "Grammatical",
        "Factual Lookup", "Vocabulary", "Pattern Recognition",
        "Associative Memory", "Logic", "Reading Comprehension",
        "Compositional", "Other",
    ]

    failed = []
    succeeded = 0

    for cat in category_order:
        task_names = by_category.get(cat, [])
        if not task_names:
            continue

        lines.append(f"\n## {cat}\n")

        for task_name in task_names:
            lines.append(f"\n### `{task_name}`\n")

            try:
                task = get_task(task_name)
            except Exception as e:
                lines.append(f"_⚠ Could not load task: {e}_\n")
                failed.append((task_name, str(e)))
                continue

            # Get examples
            try:
                examples = task.get_icl_examples(num_examples=NUM_SHOTS, seed=42)
                test_rows = task.get_split("test")
                if not test_rows:
                    lines.append("_⚠ No test instances available._\n")
                    failed.append((task_name, "empty test split"))
                    continue

                # Pick a query instance that isn't one of the demonstration examples
                demo_inputs = {ex["input"] for ex in examples}
                query = next(
                    (r for r in test_rows
                     if r.get(task.config.input_column, "") not in demo_inputs),
                    test_rows[0],
                )

                # Buildformatted prompt
                prompt = task.build_prompt(query, num_shots=NUM_SHOTS)
                answer = str(query.get(task.config.output_column, ""))

                lines.append("```\n")
                lines.append(prompt.rstrip() + "\n")
                lines.append("```\n")
                lines.append(f"\n**Expected answer:** `{answer}`\n")
                succeeded += 1

            except Exception as e:
                lines.append(f"_⚠ Error generating Example: {e}_\n")
                failed.append((task_name, str(e)))

    # Footer
    lines.append("\n---\n")
    lines.append(f"\n**{succeeded}/{len(ALL_TASKS)} tasks successfully rendered.**\n")
    if failed:
        lines.append("\n### Failed tasks\n\n")
        for name, err in failed:
            lines.append(f"- `{name}`: {err}\n")

    out_path = Path(args.output)
    out_path.write_text("".join(lines))
    print(f"✓ Saved task overview ({succeeded}/{len(ALL_TASKS)} tasks) → {out_path}")


if __name__ == "__main__":
    main()
